name: Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python and Conda enviroment
      run: |
        conda update -n base -c defaults conda
        conda env create -f requirements.yml -p env
        source $(conda info --root)/etc/profile.d/conda.sh
        conda activate ./env
        which pip
    - name: Install dependencies
      run: |
        # Activate
        source $(conda info --root)/etc/profile.d/conda.sh
        conda activate ./env
        # Pip install requirments
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements.dev.txt
    - name: Test format
      run: |
        # Activate
        source $(conda info --root)/etc/profile.d/conda.sh
        conda activate ./env
        # Make sure it is installed
        pre-commit run --all-files
    - name: Unittest
      run: |
        # Activate
        source $(conda info --root)/etc/profile.d/conda.sh
        conda activate ./env
        # Test files
        pytest -vv test.py
